# 가설 검정 : 지역별 중고 차량 가격 검정

In [ ]:
df['Location'].value_counts()

In [ ]:
groups = [df[df['Location'] == location]['Price'] for location in df['Location'].unique()]

# ANOVA 검정을 수행합니다.
anova_result = stats.f_oneway(*groups)

In [ ]:
print("ANOVA 검정 결과:")
print("검정 통계량 (F-value):", anova_result.statistic)
print("p-value:", anova_result.pvalue)

ANOVA 검정 결과:
검정 통계량 (F-value): 38.34486468655015
p-value: 8.196424841467488e-74

In [ ]:
if anova_result.pvalue < 0.05:
    print("p-value가 0.05보다 작으므로, 지역별 차량 가격이 유의미하게 다릅니다.")
else:
    print("p-value가 0.05 이상이므로, 지역별 차량 가격이 유의미하게 다르지 않습니다.")

p-value가 0.05보다 작으므로, 지역별 차량 가격이 유의미하게 다릅니다.

In [ ]:
print("정규성 검정 결과:")
for i, group in enumerate(groups):
    stat, p_value = stats.shapiro(group)
    print(f"지역 '{df['Location'].unique()[i]}'의 p-value: {p_value:.4f}")

# 등분산성 검정 (Levene Test 사용)
print("\n등분산성 검정 결과:")
stat, p_value = stats.levene(*groups)
print(f"p-value: {p_value:.4f}")

정규성 검정 결과:
지역 'Chennai'의 p-value: 0.0000
지역 'Mumbai'의 p-value: 0.0000
지역 'Delhi'의 p-value: 0.0000
지역 'Kolkata'의 p-value: 0.0000
지역 'Hyderabad'의 p-value: 0.0000
지역 'Kochi'의 p-value: 0.0000
지역 'Ahmedabad'의 p-value: 0.0000
지역 'Bangalore'의 p-value: 0.0000
지역 'Coimbatore'의 p-value: 0.0000
지역 'Pune'의 p-value: 0.0000
지역 'Jaipur'의 p-value: 0.0000

등분산성 검정 결과:
p-value: 0.0000

# 가설 검정 : 제조사별로 중고차 가격 검정

In [ ]:
brand_groups = [df[df['Brand'] == brand]['Price'] for brand in df['Brand'].unique()]
brand_groups

[0    2069.5
 Name: Price, dtype: float64,
 1      25293.84
 2      29509.48
 3      28972.94
 4      34491.60
 5      13030.16
          ...
 237    56719.52
 238    62084.88
 239    45222.32
 240    41926.46
 241    53653.60
 Name: Price, Length: 240, dtype: float64,
 242    26397.57
 243    24527.36
 244    26060.32
 245    17276.46
 246    15789.49
          ...
 510    65150.80
 511    33571.82
 512    62330.15
 513    45988.80
 514    89739.48
 Name: Price, Length: 267, dtype: float64,
 515    90444.64
 516     5748.60
 Name: Price, dtype: float64,
 517    1839.55
 518    2759.33
 519    2146.14
 520    1149.72
 521    3219.22
         ...
 633    2146.14
 634    2682.68
 635    2682.68
 636    8431.28
 637    7281.56
 Name: Price, Length: 120, dtype: float64,
 638     3832.40
 639     4138.99
 640     4752.18
 641     4982.12
 642     6055.19
 643    10270.83
 644     4583.55
 645     8799.19
 646     8477.27
 647     4752.18
 648     4215.64
 649     3449.16
 650     4077.67
 651     5334.70
 652     5518.66
 653     5074.10
 654     6116.51
 Name: Price, dtype: float64,
 655     8661.22
 656     7434.86
 657    11819.12
 658     9964.24
 659    14195.21
 660     1916.20
 661     3372.51
 662     2529.38
 663     8293.31
 664     5058.77
 665     2682.68
 666     8967.82
 667    13260.10
 668     3832.40
 669     3832.40
 670     2437.41
 671     4598.88
 672     3985.70
 673     7128.26
 674     3449.16
 675     3832.40
 676     4568.22
 677    10086.88
 682     3449.16
 683     3985.70
 684    13183.46
 Name: Price, dtype: float64,
 686    18395.52
 687    12263.68
 688    12263.68
 Name: Price, dtype: float64,
 689     8661.22
 690    11175.28
 691     9197.76
 692    12892.19
 693     4598.88
          ...
 988     2452.74
 989     1532.96
 990     1303.02
 991     1686.26
 992    87072.13
 Name: Price, Length: 298, dtype: float64,
 993      6821.67
 994      9734.30
 995      7434.86
 996      3985.70
 997      9029.13
           ...
 1610    18472.17
 1611    15176.30
 1612    14241.20
 1613    12646.92
 1614    13643.34
 Name: Price, Length: 619, dtype: float64,
 1615     2759.33
 1616     1303.02
 1617     3065.92
 1618     2912.62
 1619     1226.37
           ...
 2738    11757.80
 2739     7649.47
 2740     5288.71
 2741     4215.64
 2742     5288.71
 Name: Price, Length: 1078, dtype: float64,
 2743    24665.33
 2744    12263.68
 2745    30659.20
 Name: Price, dtype: float64,
 2746    153296.00
 2747     61318.40
 2748     58252.48
 2749     81185.56
 2750     52887.12
 2751     87348.06
 2752     79713.92
 2753    102263.76
 2754     67450.24
 2755     58252.48
 2756     45958.14
 2757     54696.01
 2758     50281.09
 2759     40623.44
 2760     41006.68
 2761     51553.44
 2762     47521.76
 2763     40623.44
 2764     39397.07
 2765     80480.40
 2766     58252.48
 2767     40654.10
 2768     36791.04
 2769     46816.60
 2770     36791.04
 2771     30659.20
 2772     24527.36
 2773     48748.13
 2774     45222.32
 2775     25416.48
 2776     44455.84
 2777     49054.72
 2778     42846.23
 2779     31425.68
 2780     55416.50
 2781     43888.64
 2782     35549.34
 2783    114972.00
 2784    121103.84
 2785    114972.00
 2786     90030.74
 2787     68983.20
 2788     77659.75
 Name: Price, dtype: float64,
 2789    27210.04
 2790    27838.55
 2791    29126.24
 2792    28359.76
 2793    30659.20
 2794    33249.90
 2795    36653.07
 2796    26826.80
 2797    30659.20
 2798    42248.38
 2799    26750.15
 2800    26090.98
 2801    29202.89
 2802    29831.40
 2803    26903.45
 2804    30674.53
 2805    25907.02
 2806    22994.40
 2807    30229.97
 Name: Price, dtype: float64,
 2808    183955.2
 Name: Price, dtype: float64,
 2809     21461.44
 2810     52120.64
 2811     63771.14
 2812     56336.28
 2813     53653.60
 2814     68216.72
 2815     90306.67
 2816     85385.87
 2817     53653.60
 2818     63617.84
 2819     86060.37
 2820     53653.60
 2821     29095.58
 2822     21308.14
 2823     36024.56
 2824     25293.84
 2825     29509.48
 2826     26826.80
 2827     30567.22
 2828     35258.08
 2829     33725.12
 2830     24144.12
 2831     30827.83
 2832     23760.88
 2833     16862.56
 2834     26826.80
 2835     25293.84
 2836     39856.96
 2837     25677.08
 2838     85477.85
 2839     45988.80
 2840     60935.16
 2841     82519.24
 2842     45881.49
 2843     55186.56
 2844     41389.92
 2845     45482.92
 2846     52887.12
 2847     49821.20
 2850    245273.60
 2851     80541.72
 2852    107307.20
 2853     91548.37
 2854     64384.32
 2855     51354.16
 2856     52243.28
 2857     67450.24
 2858     69964.29
 2859     68722.60
 2860     68615.29
 2861     61318.40
 2863    108318.95
 2864    148804.43
 2865     99259.16
 2866    102708.32
 2867     99642.40
 2868    100884.10
 Name: Price, dtype: float64,
 2869     4445.58
 2870    16111.41
 2871     6591.73
 2872     4138.99
 2873    16647.95
           ...
 3145    11435.88
 3146     4215.64
 3147    11497.20
 3148     7434.86
 3149     8967.82
 Name: Price, Length: 279, dtype: float64,
 3151    1532.96
 3152    1149.72
 3153    1379.66
 3154    1992.85
 3155    1226.37
          ...
 4399    1180.38
 4400    1532.96
 4401     843.13
 4402    2330.10
 4403    1073.07
 Name: Price, Length: 1229, dtype: float64,
 4404     21461.44
 4405     26826.80
 4406     16862.56
 4407     30275.96
 4408     19928.48
           ...
 4724    128707.32
 4725      1624.94
 4726    137966.40
 4727     85140.60
 4728     84312.80
 Name: Price, Length: 323, dtype: float64,
 4729    53653.60
 4730    68354.69
 4731    36024.56
 4732    37971.42
 4733    36484.45
 4734    55953.04
 4735    53653.60
 4736    32958.64
 4737    44379.19
 4738    45222.32
 4739    36024.56
 4740    33725.12
 4741    52120.64
 4742    48364.89
 4743    49054.72
 4744    54680.68
 4745    43689.36
 4746    33725.12
 4747    53653.60
 4748    55155.90
 4749    33633.14
 4750    33725.12
 4751    29754.75
 4752    33725.12
 4753    26060.32
 4754    60935.16
 4755    33725.12
 4756    38324.00
 4757    35258.08
 Name: Price, dtype: float64,
 4758     5901.90
 4759     4598.88
 4760     1532.96
 4761     4598.88
 4762    11497.20
 4763     8477.27
 4764    14179.88
 4765     9504.35
 4766     5288.71
 4767    12248.35
 4768    18211.56
 4769    16862.56
 4770    13413.40
 4771    15252.95
 4772    18119.59
 4773     8354.63
 4774    14026.58
 4775    52273.94
 4776    49683.23
 4777    52273.94
 4778    52273.94
 4779    49683.23
 4780    50005.16
 4781    42922.88
 4782    22994.40
 4783    19146.67
 4784    19545.24
 4785    25171.20
 4786    18165.58
 4787    48947.41
 4788    41558.55
 4789    40623.44
 4790    22994.40
 4791    22534.51
 Name: Price, dtype: float64,
 4792     5978.54
 4793     6530.41
 4794     6515.08
 4795     6131.84
 4796    10393.47
           ...
 4882    11067.97
 4883    13674.00
 4884    11880.44
 4885     9504.35
 4886    12263.68
 Name: Price, Length: 93, dtype: float64,
 4887     98109.44
 4888     73919.33
 4889     22227.92
 4890      3096.58
 4891     61318.40
 4892     70240.23
 4893    103980.68
 4894     49054.72
 4897     65779.31
 4898    110373.12
 4899    114972.00
 4900     77414.48
 4901    114972.00
 4902     93433.91
 4903     68983.20
 4904     78978.10
 Name: Price, dtype: float64,
 4905    21476.77
 4906    20694.96
 4907    20495.68
 4908    15329.60
 4909    13260.10
           ...
 5051     6131.84
 5052     7281.56
 5053     9197.76
 5054     3679.10
 5055     5595.30
 Name: Price, Length: 151, dtype: float64,
 5056     3510.48
 5057     4982.12
 5058     3357.18
 5059     2529.38
 5060     2146.14
           ...
 5233     8431.28
 5234    12248.35
 5235    11497.20
 5236    10715.39
 5237    16862.56
 Name: Price, Length: 181, dtype: float64,
 5239     8048.04
 5240     5671.95
 5241     9197.76
 5242     6131.84
 5243    18395.52
           ...
 5429     7128.26
 5430     6928.98
 5431     5671.95
 5432     6131.84
 5433     5978.54
 Name: Price, Length: 192, dtype: float64,
 5434    20694.96
 5435    49054.72
 5436     5258.05
 5437    49054.72
 5438    38324.00
           ...
 5849    40071.57
 5850    38737.90
 5851     9197.76
 5852     5365.36
 5853     5595.30
 Name: Price, Length: 420, dtype: float64,
 5856     8431.28
 5857     8400.62
 5858     7204.91
 5859     8277.98
 5860     8952.49
           ...
 6172     4598.88
 6173     8354.63
 6174     8661.22
 6175     9121.11
 6176    11880.44
 Name: Price, Length: 320, dtype: float64,
 6177    18395.52
 6178    24527.36
 6179    30659.20
 6180    38324.00
 6181    32958.64
 6182    37342.91
 6183    27056.74
 6184    11113.96
 6185    16847.23
 6186    30659.20
 6187    24527.36
 6188    33725.12
 6189    36791.04
 6190    26290.26
 6191    27976.52
 6192    21154.85
 6193    49821.20
 6194    18395.52
 6195    26336.25
 6196    36147.20
 6197    36254.50
 Name: Price, dtype: float64]

In [ ]:
f_result = stats.f_oneway(*brand_groups)
f,p = f_result.statistic.round(3), f_result.pvalue.round(3)

print("One-way ANOVA")
print("F 통계량:{}".format(f))
print("p-value:{}".format(p))

One-way ANOVA
F 통계량:295.718
p-value:0.0

In [ ]:
# statistic,p= stats.shapiro(df['A'])
# print("statistic={}, p-value={}".format(statistic,p))

## 가설 검정 owner_type에 따라 중고차량 가격이 같다.

In [ ]:
df["Owner_Type"] = df["Owner_Type"].replace({"first": 1, "second": 2, "third": 3})

In [ ]:
groups = [df[df['Owner_Type'] == owner]['Price'] for owner in df['Owner_Type'].unique()]

# ANOVA 검정을 수행합니다.
anova_result = stats.f_oneway(*groups)

# ANOVA 결과를 출력합니다.
print("ANOVA 검정 결과:")
print("검정 통계량 (F-value):", anova_result.statistic)
print("p-value:", anova_result.pvalue)

# p-value를 통해 결과를 해석합니다.
if anova_result.pvalue < 0.05:
    print("p-value가 0.05보다 작으므로, 중고차량의 횟수에 따라 가격이 유의미하게 다릅니다.")
else:
    print("p-value가 0.05 이상이므로, 중고차량의 횟수에 따라 가격이 유의미하게 다르지 않습니다.")

ANOVA 검정 결과:
검정 통계량 (F-value): 18.457253899565238
p-value: 6.455370608241317e-12
p-value가 0.05보다 작으므로, 중고차량의 횟수에 따라 가격이 유의미하게 다릅니다.